version: '2'

volumes:
  config:
  torrents:
  downloads:

services:

 transmission-daemon:
    container_name: transmission-daemon
    image: phlak/transmission
    environment:
      - TZ=America/Phoenix
    ports:
      - 9091:9091
      - 51413:51413
    volumes:
      - config:/etc/transmission-daemon
      - torrents:/srv/downloads
      - downloads:/vol/downloads
