version: '2'

volumes:
  config:
  torrents:

services:

 transmission-daemon:
    container_name: transmission-daemon
    image: phlak/transmission
    environment:
      - TZ=America/Phoenix
    ports:
      - 9091:9091
    volumes:
      - config:/etc/transmission-daemon
      - torrents:/srv/downloads
